"""Add Microsoft OAuth fields to User model

Revision ID: 27c64ed70f73
Revises: 79011a84ac36
Create Date: 2025-04-30 14:04:49.793715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c64ed70f73'
down_revision: Union[str, None] = '79011a84ac36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_token_expiry', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('microsoft_token_scopes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('microsoft_token_scopes')
        batch_op.drop_column('microsoft_token_expiry')
        batch_op.drop_column('microsoft_refresh_token')
        batch_op.drop_column('microsoft_access_token')

    # ### end Alembic commands ###
