"""Add ReminderEvent table and fields for persistent reminders

Revision ID: 4a24dd516572
Revises: 9dbdf0d093af
Create Date: 2025-04-28 11:53:10.243366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a24dd516572'
down_revision: Union[str, None] = '9dbdf0d093af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('expected_trigger_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_type', sa.Enum('TRIGGERED', 'COMPLETED', 'SKIPPED', name='reminderactiontype'), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_events_expected_trigger_time'), 'reminder_events', ['expected_trigger_time'], unique=False)
    op.create_index(op.f('ix_reminder_events_id'), 'reminder_events', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_events_reminder_id'), 'reminder_events', ['reminder_id'], unique=False)
    op.add_column('reminders', sa.Column('remind_frequency_minutes', sa.Integer(), nullable=True))
    op.add_column('reminders', sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_reminders_is_active'), 'reminders', ['is_active'], unique=False)
    op.create_index(op.f('ix_reminders_trigger_datetime'), 'reminders', ['trigger_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_trigger_datetime'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_is_active'), table_name='reminders')
    op.drop_column('reminders', 'last_notified_at')
    op.drop_column('reminders', 'remind_frequency_minutes')
    op.drop_index(op.f('ix_reminder_events_reminder_id'), table_name='reminder_events')
    op.drop_index(op.f('ix_reminder_events_id'), table_name='reminder_events')
    op.drop_index(op.f('ix_reminder_events_expected_trigger_time'), table_name='reminder_events')
    op.drop_table('reminder_events')
    # ### end Alembic commands ###
