"""Add ms_oid and ms_token_cache to User model for MSAL

Revision ID: 4a876869043e
Revises: 27c64ed70f73
Create Date: 2025-04-30 15:17:15.557441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a876869043e'
down_revision: Union[str, None] = '27c64ed70f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ms_oid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ms_token_cache', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_ms_oid'), ['ms_oid'], unique=True)
        batch_op.drop_column('microsoft_token_expiry')
        batch_op.drop_column('microsoft_token_scopes')
        batch_op.drop_column('microsoft_refresh_token')
        batch_op.drop_column('microsoft_access_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_access_token', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_refresh_token', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_token_scopes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_token_expiry', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_ms_oid'))
        batch_op.drop_column('ms_token_cache')
        batch_op.drop_column('ms_oid')

    # ### end Alembic commands ###
