"""Add Contact model and link to Task, Reminder, Note

Revision ID: 79011a84ac36
Revises: 7088664ddb48
Create Date: 2025-04-30 10:36:27.670765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79011a84ac36'
down_revision: Union[str, None] = '7088664ddb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('contacts',                       # Comment out table creation
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.Column('owner_id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_contacts_owner_id_users')), # Add name here too
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('contacts', schema=None) as batch_op: # Comment out index creation
    #     batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_contacts_name'), ['name'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_contacts_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_contact_id'), ['contact_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_notes_contact_id_contacts'), 'contacts', ['contact_id'], ['id'])

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reminders_contact_id'), ['contact_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_reminders_contact_id_contacts'), 'contacts', ['contact_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_contact_id'), ['contact_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_tasks_contact_id_contacts'), 'contacts', ['contact_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_contact_id'))
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reminders_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reminders_contact_id'))
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notes_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notes_contact_id'))
        batch_op.drop_column('contact_id')

    # Comment out dropping the contacts table indexes and table in downgrade too, 
    # as we didn't create them in the modified upgrade.
    # with op.batch_alter_table('contacts', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_contacts_owner_id'))
    #     batch_op.drop_index(batch_op.f('ix_contacts_name'))
    #     batch_op.drop_index(batch_op.f('ix_contacts_id'))
    #     batch_op.drop_index(batch_op.f('ix_contacts_email'))

    # op.drop_table('contacts')
    # ### end Alembic commands ###
