"""Add List and ListItem tables

Revision ID: a0c59b195788
Revises: 4a876869043e
Create Date: 2025-05-04 15:11:31.893662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c59b195788'
down_revision: Union[str, None] = '4a876869043e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lists_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lists_user_id'), ['user_id'], unique=False)

    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_items_list_id'), ['list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_list_items_id'))

    op.drop_table('list_items')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_user_id'))
        batch_op.drop_index(batch_op.f('ix_lists_name'))
        batch_op.drop_index(batch_op.f('ix_lists_id'))

    op.drop_table('lists')
    # ### end Alembic commands ###
