"""Add device_token to User model

Revision ID: fdc59296aacc
Revises: a006fdd896b9
Create Date: 2025-05-05 16:47:44.921845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc59296aacc'
down_revision: Union[str, None] = 'a006fdd896b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_token', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_device_token'), ['device_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_device_token'))
        batch_op.drop_column('device_token')

    # ### end Alembic commands ###
